# -*- coding: utf-8 -*-
"""AI-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbZZKw6CJIHO5nUhjT59fa0vzAHgogEN
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/fact_bookings.csv',encoding="Unicode_escape")

df.info()

df['booking_platform'].value_counts().plot(kind="bar")

df.isnull().sum()

df['no_guests'].mean()

df['no_guests'].median()

df['no_guests'].fillna(2,inplace=True)
df

df=df[df['no_guests']>0]
df.info()

df_date=pd.read_csv("/content/dim_date.csv",encoding="Unicode_escape")
df_room=pd.read_csv("/content/dim_rooms.csv",encoding="Unicode_escape")
df_aggbooking=pd.read_csv("/content/fact_aggregated_bookings.csv",encoding="Unicode_escape")
df_hotel=pd.read_csv("/content/dim_hotels_list.csv",encoding="Unicode_escape")

df_aggbooking.head()

len(df_aggbooking["property_id"].unique())



df_aggbooking.groupby("property_id")["successful_bookings"].sum()

d1=df_aggbooking["capacity"].max()
d1

df_aggbooking.groupby("property_id")["successful_bookings"].sum()

df_aggbooking[df_aggbooking["successful_bookings"]>df_aggbooking["capacity"]]["property_id"].unique()

#create occupancy_percentatge column in fact_agg_booking and find out
#which property have highest occupancy?
df_aggbooking["occupancy_percentage"]=df_aggbooking["successful_bookings"]/df_aggbooking["capacity"]*100

df_aggbooking.head()

100-df_aggbooking["occupancy_percentage"].head()

df_aggbooking[df_aggbooking['occupancy_percentage']].so

df_aggbooking.groupby("room_category")['occupancy_percentage'].mean()

df_hotel.head()

df_hotel['city'].value_counts()

df=pd.merge(df_aggbooking,df_hotel,on="property_id")
df.head(2)



df.groupby("city")['occupancy_percentage'].mean()

df_aggbooking.head()

df1=pd.merge(df_aggbooking,df_date,left_on='check_in_date',right_on="date")
df1.head()

df1[]